### PR TITLE
feat: add the implementation in R and Python

### LINKED ISSUE #2: Create a combined Rmarkdown notebook for R and Python code.

### PR DESCRIPTION
**Pull request by Sarvam-Mittal**
PR for combine file of R and python

### CODE REVIEW

**Comment by abhi18av** [comment]
@Sarvam-Mittal , yesterday I walked you through the PR rituals. Here are something for you to think about

1. Why is the name `PR` ?
2. Why did you add the label `question` when you haven't asked any question?
3. Why am I an `assignee`?

**Review by abhi18av — CHANGES_REQUESTED** [review]
Please make the requested changes and re-request the review.

**Comment by Sarvam-Mittal** [comment]
So i have to close this pull request and re-request a new one , or is there a way to edit?

**Comment by Sarvam-Mittal** [comment]
means have to edit from github console ? as not able to see any option on gitkraken..

**Comment by Sarvam-Mittal** [comment]
I have done the changes. Below are the explanation:
1) Why is the name PR ? : corrected , didn't thought properly will keep in mind 
Why did you add the label question when you haven't asked any question?: wanted to test what it does , now removed
3) Why am I an assignee?: that was error , it is basically the one who opens the PR so it should be me .
 Have done the changes and requesting you to review.

**Review by abhi18av — APPROVED** [review]

**Pull request merged**
